title: Home
email: nishanthsharmar [AT] gmail [DOT] com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nishanthsharmar
github_username:  nishanthrachakonda

# Build settings
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-include-cache

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

author:
  name             : "Nishanth Rachakonda"
  avatar           : "/assets/images/profile.jpeg"
  bio              : "Software Engineer at Google"
  location         : "Hyderabad, IN"
  github           : "nishanthrachakonda"
  links:
    - label: "Mail"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:nishanthsharmar@gmail.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/nishanthshamar"
